We thank the reviewers for their insightful feedback which will help
us improve the paper independent of the final decision here. We
perceive from the reviews that the main criticisms of the paper are in
the writing and are confident we can address these in revisions. We
first address the most pertinent technical and writing questions, and
then more minor ones. If we don't address a question below it is
because we believe the fix to it to be relatively simple.

To summarize, the most significant changes we plan to make in the
revisions are:
1. Expand on section 4.2 to more thoroughly motivate the need for our
   extensional and intensional models, e.g., lack of transitive
   reasoning and the need to reason about perturbations
2. Introduce the concrete model earlier to help motivate the abstract
   models and constructions.
3. Provide more background on the axioms for gradual typing
4. Clarify the key steps in the construction of the intensional and
   extensional model.
5. Fix the typos, and address the smaller points included below

* Reviewer 2 re-writing
*MAX:* Eric please make this more organized into distinct points.

Reviewer 2 says that the paper is difficult to follow and feels heavily
compressed. We sympathize with this viewpoint and would like to propose a few
changes that we hope will improve the exposition.

1. The main sources of confusion in the paper as it stands now is that the abstract notions
of extensional and intensional model as introduced in Section 4.2 and
defined in Section 5 are introduced without first motivating them via
concrete constructions in guarded type theory.

This leads to questions about our notion
of model, e.g., why do we need a separate notion of intensional model?
Why is it that our extensional model definition must differ from
the "idealized" definition? These issues are discussed briefly in Section 4.2, but as
Reviewer 1 points out, this section can use improvement. More specifically, in
that section we state that transitive reasoning is not possible when working
up to weak bisimilarity, and that this means that our notion of extensional model
cannot support horizontal composition of squares. We agree that this statement is
not currently justified in the paper, as pointed out by Reviewer 2 in regard to a
similar statement in Section 5.1. In particular, it would be illuminating to first
show what goes wrong if one begins with a concrete term model and tries to define
an extensional ordering relation on the guarded lift monad, i.e., an ordering "up
to delays" on either side. Such a relation is provably *not* transitive, and this
leads to the idea of decomposing the relation into two relations, weak bisimilarity
relating terms that are the same up to delay, and a /lock-step/ error ordering where
both sides must take the same number of steps (up to the left-hand side being an error).

Likewise, we state in Section 4.2 that the representability property breaks down in
the presence of observable steps. This would be easier to appreciate if we presented
(a simplified version of) the concrete intensional model and showed that one of the
simple representability properties does not hold. This would also help to motivate
the need for perturbations. In the revision, we plan to explain this as part of a
narrative that leads the reader to a more intuitive understanding of our design
choices for the abstract model.

* blah

Reviewer 1 asks why we introduce the notion of extensional model of
gradual typing and why the idealized model is unsuitable in the
setting of SGDT. Further they question why our non-transitivite
notions are necessary since weak bisimilarity for Capretta's delay
monad is transitive.

The purpose of the extensional model is to provide the categorical
structure needed to interpret the terms and inequational theory of
gradual typing. In editing we unintentionally removed some explanation
of this point.

The idealized model is unsuitable for our graduality semantics because
the semantic model of term precision that we use (≾) is provably *not
transitive*, and neither is the *guarded definition* of weak
bisimilarity (≈). The argument is as follows: if a relation ~ on L A
is

1. A congruence wrt θ: ▶_t (x t ~ y t) ⇒ θx ~ θy
2. Right-closed under delay: x ~ y ⇒ x ~ δ y
3. Transitive

Then by Löb induction you can show every element x satisfies x ~ fix
θ.  If the relation is also left-closed then this implies for any x,y
that x ~ fix θ and fix θ ~ y and so by transitivity x ~ y and the
relation is trivial. But these relations (≾, ≈) satisfy (1) and (2)
but are non-trivial so they are not transitive.

This does not contradict that Capretta's delay monad has a transitive
notion of weak bisimilarity. Capretta's weak bisimilarity should be
equivalent to the global (i.e., ∀k) version of our guarded weak
bisimilarity. This global relation therefore should be transitive. So
we almost get out an idealized model this way, but only for
"clock-irrelevant" types, which are essentially the ones that do not
use Dyn. However we need the weaker formulation of an extensional
model in order to get a compositional construction that models Dyn,
which is obviously central to gradual typing.

Finally, as briefly mentioned (378-381) transitive reasoning is not an
essential component of graduality, for instance it was not in the
original SNAPL 2015 formulation of the gradual guarantee. It was only
added in New and Licata's work which used models that supported
transitive reasoning.

* R1 why posets?
Reviewer 1 asks why the objects in our concrete model have a notion of ordering,
as opposed to just being types along with a weak bisimilarity relation. There
are two potential interpretations of this question. The first is that the reviewer
is asking why an ordering relation is needed on objects, to which our response
is that we are trying to model the term precision ordering of gradual typing.
In particular, the abstract models include a notion of commutative squares
between morphisms, and the way we instantiate in the concrete setting is by
equipping the objects with a partial order which then extends to the morphisms,
i.e., we define a commuting square f ⊑ g as "if x ≤ y then f x ≤ g y".

The second interpretation of the question about the ordering is that the reviewer
is asking why we cannot treat the ordering "synthetically" in the same way that
we treat the step-indexing synthetically via SGDT. That is, our objects would be
treated as sets when working internally, but from an "external viewpoint" they
would be sets equipped with a partial order. This is an interesting possibility
which, as we mention in the Discussion section of the paper, we plan to explore
as future work.

* R1 why weak bisimilarity?
Reviewer 1 also asks why all of the objects in our concrete model need to come
equipped with a notion of weak bisimilarity. That is, why can't weak
bisimilarity be limited to the guarded lift monad? Tracing things back one step,
we could say that this is because the intensional model requires the vertical
hom-sets to have a notion of "weak bisimilarity", which in this abstract setting
is specified as a reflexive, symmetric relation that is closed under composition.
As was the case with the partial order discussed above, when we define the
concrete model, we need to satisfy this requirement. We do so by equipping the
*objects* with a reflexive, symmetric relation, which then extends to a relation
on the vertical hom-sets (morphisms between predomains) in the obvious way.

Of course, one could now ask, as Reviewer 1 does, why the definition of
intensional model is designed this way. The reason the definition of
intensional model requires a notion of weak bisimilarity for all vertical
hom-sets is that we need to reason about weak bisimilarity for
*higher-order* types, e.g., when we cast a function to another function,
no steps are taken at a first-order. But when the function is applied,
steps may be taken. So we need a way to lift the bisimilarity relation
to functions.

* R1 loves Agda

Reviewer 1 mentions that they would prefer if the Agda formalization
was complete.

We are planning to complete at least some portions of the results here
in guarded cubical Agda, especially the adequacy
results. Unfortunately, there is still significant effort to finish
the mechanization as a faithful rendering of the constructions in our
paper would rely on formalizations of double categories and CBPV
models, which are not readily available.

On the other hand, we would like to emphasize that we co-designed the
concrete model with the formalization in Agda and this was immensely
helpful for the authors to better understand guarded type theory and
domain theory, even without a complete mechanization.

* Other

> By the way, is this a variation of double category that appeared before in the literature?

We are not aware of a name for this variation from an existing source.

  
> lines 720-727, you do not really say what changes in an intensional model when we give up
> horizontal composition being a strict CBPV morphism. You only say that now m_V and m_E are
> CBPV morphisms, while before they where strict. So what changes concretely?

Composition is only a lax morphism because relation constructors
generally do not commute strongly strongly with relation
composition. Specifically, ->, U and F only laxly commute with our
notion of relation composition. This is already true of the action of
the function arrow on ordinary relations.

* ℕ in Perturbations

> Section 5.3.1, when extending F with perturbations, you have `ℕ × P_A` instead of
> simply `P_A`. Can you comment on why you have the cartesian product with natural
> numbers here? What breaks if you do not add it and simply take P_A? It is not
> immediately clear to me by quickly reading through Appendix C.1.

*MAX:* point to line 1191 for an explanation

TODO - check

The ℕ comes from the fact that in the concrete model, a projection morphism
may "wait", i.e., introduce a θ to construct an element of type L℧ A.
So a perturbation on FA also needs a way to "delay" in order to mimic this
waiting, and we accomplish this by defining such a perturbation to be
a pair of a natural number n, with a perturbation p_A on A. The interpretation
of this perturbation as an endomorphism on FA is to perform the perturbation
on A (under the functorial action of F) and then perform a delay n-times
(where the existence of a delay operation is part of the data of the model).

* Minor Qs

From Reviewer 2:

> l289: The use of the tick calculus is great in Agda but it is really
> impossible to work with on paper because the structural rules for
> when one can apply a tick are far too subtle to check by hand — as
> anyone who has ever been surprised by a Guarded Cubical Agda error
> message can attest. I think that it would be important here to
> mention some of the constraints on tick variables, lest the reader
> get the impression that they can just apply them freely.

  TODO - check
  
  This is a good point. We will mention the constraints on tick application
  in the technical background section in the revision.

> l341: Is this admissibility claim proved somewhere?

Yes, this is proven in Appendix A.
  
> l378: Can the benefit of transitivity being admissible instead of
> derivable be explained? ...

This was a bit unclearly worded: reflexivity is admissible from
congruence so we don't bother adding it as a primitive. Transitivity
is *not* admissible, and this is desired as our extensional models
(Section 5.1) do not model transitivity.

> l388: The point about upcasts and downcasts being some kinds of
> least upper bounds and greatest lower bounds is interesting ... Is
> it just that these are basically adjoints or some kind?

Yes, the technical content of this intuition is that they are Galois
connections, which can be formulated as saying they are given
pointwise by a certain join/meet.

> l515: Categories internal to the category of CBPV models are
> invoked, but to make sense of this, don’t we need there to be
> pullbacks of CBPV models? I believe the idea must be “CBPV is an
> essentially algebraic theory, so the category of CBPV models and
> strict morphisms is locally presentable and thus complete”. Perhaps
> this could be remarked on.

Yes, this argument is exactly what we had in mind.

> l551: Is Definition 4.2 a universal property for ‘f’, or can there
> be more than one representative?

Yes, in the sense that Definition 4.2 characterizes f up to order
equivalence.

> l603: It occurred to me that maybe virtual double categories could
> be a useful intermediate abstraction here? I am curious if you
> thought about that.

We had considered this but didn't have any use for the more general
2-cells in modeling graduality so we used the simpler reflexive graph
categories.

> l715: in order to speak of categories internal to CBPV with lax
> morphisms, we need that category to have pullbacks. Is that
> obviously deducible from the completeness of the category of CBPV
> models with strict morphisms?

*MAX:* I'll look into this tomorrow
TODO

* 1-Topos of Trees
> l1070, l1081: here is something that is extremely sensitive to the
> chosen model of guarded recursion, which needs to be discussed. In
> the topos of trees (or the (∞,1)-topos of trees if you prefer), a
> *relation* defined this way is actually trivial: in the internal
> *logic* (subobject doctrine), it appears that every element of the
> guarded lifting monad terminates. To avoid this and remain
> compatible with a topos-of-trees model, one needs to use structure
> instead of property (as Paviotti did), but this is of course not
> compatible with the viewpoint of partial orders; another option that
> lets you have mere propositions may be to consider step-indexing
> over a bigger ordinal. It so happens that this problem does not
> arise at all (if I recall correctly) in the nonstandard models of
> guarded cubical type theory obtained from presheaves on the product
> of the cube category with the natural numbers (which is, indeed, the
> intended semantics of guarded cubical agda); in that case, you can
> get a non-trivial mere predicate that refers to convergence. But
> this model is not the (∞,1)-topos of trees, which instead seems to
> arise as some kind of localisation thereof; roughly what is
> happening is that there is a difference between taking strict
> presheaves and taking (∞,1)-presheaves — and the former, naturally,
> has no known universal property in the world of (∞,1)-categories.
> Anyway, all this is very important and it would be good to be
> explicit about what which models of Higher SGDT do and don’t
> trivialise the notions employed in the present work.

This is a fair point of discussion that we hadn't previously
considered and we appreciate the reviewer for pointing it out. This is
a subtle issue so here is a concise overview of the situation:

1. Our treatment was based on the Greatest HITs paper which uses the
   (∞,1)-topos of trees as a model where this is not an issue, the
   question is if the development could be modified to be more
   portable to other guarded type theories/models.
2. In the 1-topos of trees model our definition of weak bisimilarity
   and our closure of lock-step error ordering under weak bisimilarity
   are trivial due to the combination of
   relating terms with differing numbers of steps and using propositional
   truncation.
   However the lock-step error ordering doesn't allow differing
   numbers of steps or require an existential quantifier, and has a
   non-trivial semantics even in the 1-topos model. So there is no
   issue with using posets for strong ordering, only in forcing
   notions using weak bisimilarity to be propositions.
3. We have studied this issue since the reviews and we are confident
   that allowing weak bisimilarity to be a Set rather than a Prop
   would not impact any of the results of the paper, as we only use
   them as inputs to the adequacy theorem, whose output is a
   Prop. This change would allow us to remove dependence on induction
   under clocks from Greatest HITs in the paper and corresponding
   axioms in our ongoing Agda formalization.

> line 1034-1040, this definition seems to indicate that your relations are
proof-relevant in the model. Is this the case?

We did not mean to imply that this relation was Set-valued, this was
intended to be an inductively defined proposition.

*MAX:* squash previous two answers

> The paper makes use of Ticked Cubical Type Theory (TCTT). Several features of TCTT
> are already present in Clocked Type Theory (as presented in "The Clocks Are Ticking:
> No More Delays!" by Bahr, Grathwohl, and Møgelberg). How much of the paper could one
> reconstructed in Clocked Type Theory, and what advantages does TCTT offer over Clocked
> Type Theory in this work?

  TODO - check

  The main difference between TCTT and Clocked Type Theory appears to be the
  presence of the path equality of cubical type theory in the former.
  In Clocked Type Theory, the unfolding of guarded fixpoints is a definitional
  equality, whereas in the setting of TCTT this unfolding is only true up to a
  path. However, the constructions carried out in this paper work in either case,
  so everything we do in this paper should be possible in Clocked Type Theory.

  The main benefit of working in TCTT is that we have access to the nice features
  of cubical type theory, e.g., function extensionality is provable, and this
  implies extensionality results for the later type and for clocks since
  these are just Pi types.

*MAX:* squash with previous as well?
